id: P000579
initial_creation_type: ocr
source_metadata:
  id: bdr:W30106
  title: གྲུབ་ཆེན་བརྒྱད་ཅུའི་རྣམ་ཐར་དང་ཞལ་ཐང་།
  author: ''
  volumes:
    5b70bc0ffb18498bbf8ece95cbe89455:
      image_group_id: I1KG13743
      title: Volume 1 of grub chen brgyad cu'i rnam thar dang zhal thang /
      volume_number: 1
      total_pages: 236
      base_file: v001.txt
ebook_metadata:
  title: གྲུབ་ཆེན་བརྒྱད་ཅུའི་རྣམ་ཐར་དང་ཞལ་ཐང་།
  author: ''
  sku: P000579
  cover: cover.jpg
  layers:
  - pagination
