id: P000579
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:48:08.345759
source_metadata:
  id: bdr:W30106
  title: གྲུབ་ཆེན་བརྒྱད་ཅུའི་རྣམ་ཐར་དང་ཞལ་ཐང་།
  author: ''
  volumes:
    5b70bc0ffb18498bbf8ece95cbe89455:
      image_group_id: I1KG13743
      title: Volume 1 of grub chen brgyad cu'i rnam thar dang zhal thang /
      volume_number: 1
      total_pages: 236
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
