id: IB828EED2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T13:21:35+00:00'
last_modified: '2022-06-07T12:22:24.404837+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30106
  title: གྲུབ་ཆེན་བརྒྱད་ཅུའི་རྣམ་ཐར་དང་ཞལ་ཐང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5B7B:
      image_group_id: I1KG13743
      title: Volume 1 of grub chen brgyad cu'i rnam thar dang zhal thang /
      total_pages: 236
      order: 1
      base_file: 5B7B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
